name: prRONTo
channels:
  - conda-forge
  - bioconda
  - piechottam
dependencies:
  - snakemake
  - scikit-learn=0.24.2
  - pandas
  - click
  - samtools
  - jacusa2
  - r-base
  # - r-optparse
  # - r-jacusa2helper
