name: prRONTo
channels:
  - conda-forge
  - bioconda
  - piechottam
dependencies:
  - snakemake
  - scikit-learn=0.24.2
  - pandas
  - click
  - samtools
  - jacusa2
  - r-base
  - r-optparse
  - r-ggplot2
  - r-xtable
  - r-tidyverse
  - r-knitr
  - r-kableExtra
  - r-ggpubr
  - r-complexupset
  - bioconductor-plyranges
  - bioconductor-bsgenome
  - r-jacusa2helper
  - r-ggh4x
