name: prRONTo
channels:
  - conda-forge
  - bioconda
  - piechottam
dependencies:
  - snakemake
  - scikit-learn=0.24.2
  - pandas
  - click
  - samtools
  - jacusa2
  - r-base
  - knitr
  - rmarkdown
  - r-optparse
  - r-ggplot2
  - r-xtable
  - r-tidyverse
  - r-knitr
  - r-ggpubr
  # - r-jacusa2helper
